version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0

workflows:
  sample:
    jobs:
      - node/test:
          version: '15.1'
          post-steps:
            - aws-s3/copy:
                from: dist/
                to: s3://s3://devsdecide.com
                arguments: --recursive