version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0
  path-filtering: circleci/path-filtering@0.1.1


jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout:
          path: ~/repo
      - run: mkdir bucket
      - run: mv *html bucket/
      - run: mv css bucket/
      - run: mv img bucket/
      - aws-s3/copy:
          arguments: '--recursive'
          from: bucket
          to: 's3://devsdecide.com'
workflows:
    baseworkflow:
      jobs:
        - build:
            filters: 
              branches:
                only: master 