version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0

workflows:
  sample:
    jobs:
      - run:
          name: Tag and Push Image
          command: |
            ls
#      - aws-s3/copy:
#          from: .
#          to: s3://devsdecide.com
#          arguments: --recursive

