version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0
  path-filtering: circleci/path-filtering@0.1.1
  node: circleci/node@5.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - node/install-packages
      - save_cache:
          paths:
            - ~/
          key: k-{{ .Revision }}
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - restore_cache:
          keys:
            - k-{{ .Revision }}
      - run: mkdir bucket
      - run: mv *html bucket/
      - run: mv css bucket/
      - run: mv img bucket/
      - aws-s3/copy:
          arguments: '--recursive'
          from: bucket
          to: 's3://devsdecide.com'
  deploy2:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - restore_cache:
          keys:
            - k-{{ .Revision }}
      - aws-s3/copy:
          arguments: '--recursive'
          from: bucket
          to: 's3://devsdecide.com'
workflows:
    baseworkflow:
      jobs:
        - build:
            filters:
              branches:
                ignore: gh-pages
        - deploy:
            filters: 
              branches:
                only: master
            requires:
             - "build"
        - deploy2:
            filters:
              branches:
                only: gh-pages