version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0

workflows:
  deploy:
    jobs:
      - run: "ls"
      - aws-s3/copy:
          from: .
          to: s3://devsdecide.com
          arguments: --recursive

