jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket
      - run: mv *html bucket/
      - run: mv css bucket/
      - aws-s3/copy:
          arguments: '--recursive'
          from: bucket
          to: 's3://devsdecide.com'
      - aws-cloudfront:
          distribution_id: E2U5QRJGNRO0KP
          paths: *
orbs:
  aws-s3: circleci/aws-s3@2.0
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0
version: 2.1