jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkidr bucket
      - run: mv *html bucket/
      - run: mv css bucket/
      - aws-s3/copy:
          arguments: '--recursive'
          from: bucket
          to: 's3://devsdecide.com'
orbs:
  aws-s3: circleci/aws-s3@2.0
version: 2.1