name: Deploy

on:
  push:
    branches:
      - master
      - gh-pages

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: aws s3 sync . s3://devsdecide.com --exclude ".git/*" --exclude ".github/*"

      - run: aws cloudfront create-invalidation --distribution-id E2U5QRJGNRO0KP --paths "/*"

  deploy2:
    if: github.ref == 'refs/heads/gh-pages'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: aws s3 sync . s3://devsdecide.com --exclude ".git/*" --exclude ".github/*"
